match_names = [
    "libtesseract",
    "tesseract",
]
pc = "tesseract"
system = "cmake"
needs = [
    "leptonica",
]
cmake_args = [
    "-DBUILD_SHARED_LIBS=ON",
    "-DSW_BUILD=OFF",
    "-DENABLE_TRAINING=OFF",
    "-DBUILD_TRAINING_TOOLS=OFF",
    "-DUSE_OPENMP=OFF",
    "-DCMAKE_PREFIX_PATH={prefix}",
]

[source]
type = "tar"
url = "https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.5.0.tar.gz"
sha256 = "f2fb34ca035b6d087a42875a35a7a5c4155fa9979c6132365b1e5a28ebc3fc11"

[triplet_overrides.mingw-x86_64-llvm]
prefixup = "sed -i 's/set(LIB_Ws2_32 Ws2_32)/set(LIB_Ws2_32 ws2_32)/' {src}/CMakeLists.txt"
