match_names = [
    "libsdl2",
    "sdl2",
]
pc = "sdl2"
system = "cmake"
cmake_args = [
    "-DSDL_SHARED=ON",
    "-DSDL_STATIC=OFF",
    "-DSDL_TEST_LIBRARY=OFF",
]

[source]
type = "git"
url = "https://github.com/libsdl-org/SDL.git"
rev = "release-2.30.9"
