match_names = [
    "lcms2",
    "lcms",
]
pc = "lcms2"
system = "makefile"
configure_args = []
make_args = [
    "LDFLAGS=-no-undefined",
]

[source]
type = "tar"
url = "https://github.com/mm2/Little-CMS/releases/download/lcms2.19.1/lcms2-2.19.1.tar.gz"
sha256 = "bfc54f7bab59fbc921012014a8032e4cba4abd46db47d46b76416a8c0b2815c8"
