match_names = [
    "dvdnav",
    "libdvdnav",
]
pc = "dvdnav"
system = "makefile"
needs = [
    "libdvdread",
]
configure_args = []
make_args = [
    "LDFLAGS=-no-undefined",
]

[source]
type = "tar"
url = "https://download.videolan.org/pub/videolan/libdvdnav/6.1.1/libdvdnav-6.1.1.tar.bz2"
sha256 = "c191a7475947d323ff7680cf92c0fb1be8237701885f37656c64d04e98d18d48"
