platforms = [
    "linux",
]
match_names = [
    "libdc1394",
    "dc1394",
    "libdc1394-2",
]
pc = "libdc1394-2"
system = "makefile"
needs = [
    "libraw1394",
    "libavc1394",
]
configure_args = []

[source]
type = "tar"
url = "https://downloads.sourceforge.net/project/libdc1394/libdc1394-2/2.2.7/libdc1394-2.2.7.tar.gz"
sha256 = "537ceb78dd3cef271a183f4a176191d1cecf85f025520e6bd3758b0e19e6609f"
