"""Post-install fixups, phase-3 shape.

Two layers, both keyed by locality:
  1. automatic hygiene -- generic, idempotent normalizations applied to
     every port (share-side .pc relocation, mingw DLL staging, generated
     .pc for data-declared-but-unshipped pkg-config entries);
  2. per-port fixup -- ports/<key>/fixup.py with run(ctx, key, dep).
     Its existence is the declaration; there is no registry and no
     "fixups" list in port.toml anymore.

Discipline: prefer fixing the recipe or the backend; a per-port fixup is
the last resort for a port-specific install bug, and its docstring is
the reason field of that workaround.
"""

import importlib.util
import os

from . import paths


def _share_pc(ctx):
    """Projects staging .pc into share/pkgconfig: relocate. The triplet
    PKG_CONFIG_PATH and the validate gate only scan lib/pkgconfig."""
    prefix = ctx["prefix"]
    src_dir = os.path.join(prefix, "share", "pkgconfig")
    dst_dir = os.path.join(prefix, "lib", "pkgconfig")
    if not os.path.isdir(src_dir):
        return
    os.makedirs(dst_dir, exist_ok=True)
    import glob as _glob
    import shutil
    for pc in _glob.glob(os.path.join(src_dir, "*.pc")):
        dst = os.path.join(dst_dir, os.path.basename(pc))
        if not os.path.exists(dst):
            shutil.copy2(pc, dst)
            print("hygiene share_pc: {} -> {}".format(
                os.path.basename(pc), dst_dir))


def _mingw_bin_dlls(ctx):
    """Some mingw installs stage only the import library (lib/x.dll.a)
    while the runtime DLL stays in the build tree. For every import lib
    in <prefix>/lib, look for the matching DLL in the port build tree
    and copy it to <prefix>/bin, where PE loaders search. Idempotent."""
    if ctx["triplet_cfg"].get("target_os") != "mingw32":
        return
    prefix = ctx["prefix"]
    libdir = os.path.join(prefix, "lib")
    import glob as _glob
    import shutil
    for implib in _glob.glob(os.path.join(libdir, "*.dll.a")):
        name = os.path.basename(implib)[:-len(".dll.a")] + ".dll"
        dst = os.path.join(prefix, "bin", name)
        if os.path.exists(dst):
            continue
        bdir = paths.port_build_dir(ctx["root"], ctx["triplet"],
                                    ctx.get("key", ""))
        hits = _glob.glob(os.path.join(bdir, "**", name), recursive=True)
        if hits:
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(hits[0], dst)
            print("hygiene mingw_bin_dlls: {} -> bin/".format(name))


def _simple_pc(ctx, key, dep):
    """A port declaring pc/pc_libs but installing no .pc gets a minimal
    generated one -- the validate gate resolves every port through one.
    Ancient upstreams (flite, gsm, ...) simply predate pkg-config.
    Host tools have no consumer .pc and are exempt."""
    if dep.get("tool"):
        return
    pc = dep.get("pc", key)
    if not dep.get("pc_libs") and os.path.isfile(os.path.join(
            ctx["prefix"], "lib", "pkgconfig", pc + ".pc")):
        return
    pcdir = os.path.join(ctx["prefix"], "lib", "pkgconfig")
    os.makedirs(pcdir, exist_ok=True)
    path = os.path.join(pcdir, pc + ".pc")
    if os.path.isfile(path):
        return
    libs = " ".join(dep.get("pc_libs", ["-l" + pc]))
    body = (
        "prefix={p}\n"
        "exec_prefix=${{prefix}}\n"
        "libdir=${{prefix}}/lib\n"
        "includedir=${{prefix}}/include\n\n"
        "Name: {name}\n"
        "Description: {name} (pc generated by ffmake)\n"
        "Version: 1.0\n"
        "Libs: -L${{libdir}} {libs}\n"
        "Cflags: -I${{includedir}}\n"
    ).format(p=ctx["prefix"], name=pc, libs=libs)
    with open(path, "w") as f:
        f.write(body)
    print("hygiene simple_pc: wrote {} (Libs: {})".format(path, libs))


def apply(ctx, key, dep):
    ctx = dict(ctx)
    ctx["key"] = key
    _share_pc(ctx)
    _mingw_bin_dlls(ctx)
    _simple_pc(ctx, key, dep)
    path = os.path.join(ctx["root"], "ports", key, "fixup.py")
    if not os.path.isfile(path):
        return
    spec = importlib.util.spec_from_file_location(
        "ffmake_port_fixup_" + key, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    mod.run(ctx, key, dep)
