match_names = [
    "libgme",
    "gme",
]
pc = "libgme"
system = "cmake"
cmake_args = [
    "-DBUILD_SHARED_LIBS=ON",
    "-DBUILD_EXAMPLES=OFF",
    "-DENABLE_UBSAN=OFF",
]

[source]
type = "tar"
url = "https://github.com/libgme/game-music-emu/archive/refs/tags/0.6.3.tar.gz"
sha256 = "4c5a7614acaea44e5cb1423817d2889deb82674ddbc4e3e1291614304b86fca0"
