match_names = [
    "librist",
    "rist",
]
pc = "librist"
system = "meson"
needs = [
    "mbedtls",
]
meson_args = [
    "-Duse_mbedtls=true",
    "-Dtest=false",
]

[source]
type = "tar"
url = "https://code.videolan.org/rist/librist/-/archive/v0.2.10/librist-v0.2.10.tar.gz"
sha256 = "797e486961cd09bc220c5f6561ca5a08e7747b313ec84029704d39cbd73c598c"
