match_names = [
    "xeve",
]
pc = "xeve"
system = "cmake"
cmake_args = [
    "-DBUILD_SHARED_LIBS=ON",
]

[source]
type = "git"
url = "https://github.com/mpeg5/xeve.git"
rev = "4325639f8dff8274c023df3d7c1ca6d3cdcfc11b"
