"""simple_pc fixup: minimal pkg-config file for ancient ports that install
no .pc of their own (the validate gate resolves every port through one).
Reads the pc name from the entry ("pc") and link flags from an optional
"pc_libs" list entry ("pc_libs": "-lflite -lm"). Idempotent.
"""

import os


def run(ctx, key, dep):
    prefix = ctx["prefix"]
    pc = dep.get("pc", key)
    pcdir = os.path.join(prefix, "lib", "pkgconfig")
    os.makedirs(pcdir, exist_ok=True)
    path = os.path.join(pcdir, pc + ".pc")
    if os.path.isfile(path):
        return
    libs = " ".join(dep.get("pc_libs", ["-l" + pc]))
    body = (
        "prefix={p}\n"
        "exec_prefix=${{prefix}}\n"
        "libdir=${{prefix}}/lib\n"
        "includedir=${{prefix}}/include\n\n"
        "Name: {name}\n"
        "Description: {name} (pc generated by ffmake)\n"
        "Version: 1.0\n"
        "Libs: -L${{libdir}} {libs}\n"
        "Cflags: -I${{includedir}}\n"
    ).format(p=prefix, name=pc, libs=libs)
    with open(path, "w") as f:
        f.write(body)
    print("fixup simple_pc: wrote {} (Libs: {})".format(path, libs))
