match_names = [
    "lilv",
    "lilv-0",
]
pc = "lilv-0"
system = "meson"
needs = [
    "serd",
    "sord",
    "sratom",
    "zix",
    "lv2",
]
meson_args = [
    "-Dtests=disabled",
    "-Ddocs=disabled",
]

[source]
type = "tar"
url = "https://download.drobilla.net/lilv-0.24.26.tar.xz"
sha256 = "22feed30bc0f952384a25c2f6f4b04e6d43836408798ed65a8a934c055d5d8ac"
