match_names = [
    "libxcb",
    "xcb",
    "libxcb_shape",
    "libxcb_shm",
    "libxcb_xfixes",
]
pc = "xcb"
system = "makefile"
strict_pkgconfig = false
needs = [
    "xcb-proto",
    "libxau",
    "libxdmcp",
]
configure_args = []
make_args = [
    "LDFLAGS=-no-undefined",
]

[source]
type = "tar"
url = "https://xorg.freedesktop.org/archive/individual/xcb/libxcb-1.17.0.tar.xz"
sha256 = "599ebf9996710fea71622e6e184f3a8ad5b43d0e5fa8c4e407123c88a59a6d55"
