platforms = [
    "linux",
]
match_names = [
    "libavc1394",
    "avc1394",
    "rom1394",
]
pc = "libavc1394"
system = "makefile"
needs = [
    "libraw1394",
]

[source]
type = "tar"
url = "http://deb.debian.org/debian/pool/main/liba/libavc1394/libavc1394_0.5.4.orig.tar.gz"
sha256 = "7cb1ff09506ae911ca9860bef4af08c2403f3e131f6c913a2cbd6ddca4215b53"
