match_names = [
    "libilbc",
    "ilbc",
]
pc = "libilbc"
system = "cmake"
cmake_args = []

[source]
type = "tar"
url = "https://github.com/TimothyGu/libilbc/releases/download/v3.0.3/libilbc-3.0.3.tar.gz"
sha256 = "47c57deb26a36da11cbf7d51e76894c7b909ab007664f736319267bde57c73d0"
