match_names = [
    "lv2",
]
pc = "lv2"
system = "meson"
meson_args = [
    "-Ddocs=disabled",
    "-Dtests=disabled",
]

[source]
type = "tar"
url = "https://lv2plug.in/spec/lv2-1.18.10.tar.xz"
sha256 = "78c51bcf21b54e58bb6329accbb4dae03b2ed79b520f9a01e734bd9de530953f"
